@startuml
actor Admin
rectangle "Admin Panel" as AP {
	[nginx]
	[webserver]
	[proxy API] as API

	Admin -> nginx
	nginx -> webserver
	webserver --> API
}

rectangle "Automation platform (Zapier)" {
	[trigger]
	[action]
	trigger -> action
}

Admin -> trigger

action -> API

rectangle ETL {
	folder "Airflow DAGs" as dag
	[Airflow API] as airflow
	API --> airflow


	database DataLake
	database DWH
	database "DWH replica" as replica

	airflow -> dag

	dag --> DataLake
	dag --> DWH
	DWH --> replica
}
@enduml