@startuml
!include <C4/C4_Container>
Person(Admin, "Admin", )

System_Ext(ERP, "ERP",) {
	database ERP_prod
	database ERP_replica
	ERP_prod --> ERP_replica
}

System_Boundary(c1,"Сервис централизованной аналитики" ) {
	Container(AP,"Admin Panel") {
		[nginx]
		[webserver]
		[proxy API] as API

		Admin --> nginx
		nginx --> webserver
		webserver --> API
	}

	Container(ETL, "оркестратор задач", "Airflow" ) {
		folder "Airflow DAGs" as dag {
			file InputDAG
			file OutputDAG
		}
		[Airflow API] as airflow
	}
		API --> airflow
                airflow --> dag

		ContainerDb(DataLake, "DataLake")
		ContainerDb(DWH, "DWH")
		ContainerDb(DWH_replica, "DWH_replica")

		ERP_replica --> InputDAG
		InputDAG --> DataLake
		DataLake --> DWH

		DWH --> DWH_replica
		DWH_replica --> OutputDAG
		OutputDAG --> ERP_prod
}

System_Ext(Automation,"Automation platform","(Zapier)") {
	[trigger]
	[action]
	trigger --> action
}
Admin --> trigger
action --> API
@enduml
