@startuml
actor Admin

rectangle ERP {
	database ERP_prod
	database ERP_replica
	ERP_prod --> ERP_replica
}

rectangle "Сервис централизованной аналитики"  {

	rectangle "Admin Panel" as AP {
		[nginx]
		[webserver]
		[proxy API] as API

		Admin --> nginx
		nginx --> webserver
		webserver --> API
	}

	rectangle "оркестратор задач (Airflow)" as ETL {
		folder "Airflow DAGs" as dag {
			file InputDAG
			file OutputDAG
		}
		[Airflow API] as airflow
		API --> airflow
                airflow --> dag


		database DataLake
		database DWH
		database DWH_replica

		ERP_replica --> InputDAG
		InputDAG --> DataLake
		DataLake --> DWH

		DWH --> DWH_replica
		DWH_replica --> OutputDAG
		OutputDAG --> ERP_prod
	}
}



rectangle "Automation platform (Zapier)" {
	[trigger]
	[action]
	trigger --> action
}
Admin --> trigger
action --> API


@enduml
