@startuml
start
:xlsx;
:save data source;
:parse;
#gold:validate individual rows;
if (separate invalid records) then (invalid records)
	#gold:generate report;
	:send report to manager;
	stop
else (valid records)
	:update staging DB;
	#gold:run tests with agregates;
	if (pass tests) then (has errors)
		#gold:generate report;
		:send report to manager;
		stop
	else (no errors)
		if (partial update flag) then (False)
			:wait full valid batch;
			stop
		else (True)
			if (wait for approval flag) then (True)
				#gold:send form to manager;
				stop
			else (no need to approve)
				:update WH;
				:transform data for BI;
				:update data in DataMart;
				:BI dashboard;
			endif
		endif
	endif
endif
stop
@enduml
