@startuml
left to right direction
actor Admin  
rectangle ETL {
	usecase "задаю правила загрузки" as UC1
	usecase "задаю правила выгрузки данных" as UC2
	usecase "задаю правила трансформации данны" as UC3
	usecase "задаю правила проверки данных" as UC4
	usecase "я останавливаю ETL" as UC5
	usecase "запускаю ETL" as UC6
	usecase "я задаю расписание выполнения ETL" as UC7
	usecase "я получаю список существующие ETL" as UC8


	Admin -- UC1 
	Admin -- UC2 
	Admin -- UC3 
	Admin -- UC4 
	Admin -- UC5 
	Admin -- UC6 
	Admin -- UC7 
	Admin -- UC8 
}
@enduml